language: php
sudo: true
dist: bionic
php:
  - '8.1.0'

before_install:
  - composer self-update
  - composer validate

install:
  - composer update --prefer-dist --no-interaction

script:
  -  php --version
  - ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml --coverage-clover clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:

    - stage: Test
      php: 8.1.0
      env: DB=mysql
      services:
        - mysql
    - php: 7.3
      env: DB=mysql
      services:
        - mysql

    - php: 8.1.0
      env: DB=pgsql POSTGRESQL_VERSION=12
      services:
        - postgresql


    - php: 7.3
      env: DB=pgsql POSTGRESQL_VERSION=12
      services:
        - postgresql



    - php:  8.1.0
      env: DB=sqlsrv
      sudo: required
      services:
        - docker
      before_script:
        - bash ./tests/travis/install-mssql-sqlsrv.sh
        - bash ./tests/travis/install-mssql.sh
    - php: 7.3
      env: DB=sqlsrv
      sudo: required
      services:
        - docker
      before_script:
        - bash ./tests/travis/install-mssql-sqlsrv.sh
        - bash ./tests/travis/install-mssql.sh
